ttc_brake_manager:
  ros__parameters:
    joy_topic: /joy
    scan_topic: /scan
    cmd_topic: /ackermann_cmd
    brake_topic: /commands/motor/brake
    drive_enable_topic: /drive_enable
    safety_drive_topic: /safety/drive

    stop_on_soft_brake: true
    stop_on_brake_hold: false #true applies break when no gas is given

    enable_brake_hold: false #brake applied without gas 
    stop_speed_threshold: 0.10
    brake_hold: 5.0  #invoked is brakehold enabed 

    # Verify indices with: ros2 topic echo /joy --once
    l1_button_index: 4
    l2_axis_index: 3 #L2 = 3
    l2_axis_mode: auto     # auto | 0_to_1 | 1_to_minus1
    soft_brake_deadzone: 0.08

    # Brake tuning
    hard_brake: 45.0 #45 A
    soft_brake_max: 30.0 

    # TTC tuning
    ttc_enabled: false
    ttc_threshold: 0.55 #collison in >0.55 sec (race =0.30-0.5), indoor = 0.6 -0.7
    ttc_release_threshold: 0.80 # hysteresis (relase brake when ttc > .80)
    ttc_min_speed: 0.40 #ttc is ignored below 0.4 m/s
    front_angle_deg: 30.0 #front lidar beams used
    ttc_min_range: 0.20 #ignored very close readings from bumber
    emergency_hold_time: 0.35
    
    debug_brake_mode: true
    debug_ttc: true
    debug_ttc_rate_sec: 0.5

    publish_rate: 50.0
