<?xml version="1.0"?>
<package format="3">
  <name>rrt_planner</name>
  <version>0.0.1</version>
  <description>RRT-based local planner for F1TENTH autonomous car.</description>

  <maintainer email="john@purdue.edu">John Orina</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>ackermann_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
