joy_node:
  ros__parameters:
    device_id: "/dev/input/js0"
    deadzone: 0.05
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:

    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop_unmixed
      axis_mappings:
        drive-speed:
          axis: 4       # R2 (unused here)
          scale: 0.0    # disabled
          offset: 0.0

        drive-steering_angle:
          axis: 2
          scale: 0.0
          offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop_unmixed
      deadman_buttons: [4]    # L1
      axis_mappings:

        # throttle disabled here, handled by throttle_mix
        drive-speed:
          axis: 4
          scale: 1.0
          offset: 0.0

        # right stick left/right
        drive-steering_angle:
          axis: 2
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Int8
      topic_name: /dev/null
      deadman_buttons: [5]     # R1 (handbrake)
      message_value:
        data:
          value: 0
