# Hokuyo UST-20LX (Ethernet)
hokuyo:
  ros__parameters:
    ip_address: "192.168.0.10"
    ip_port: 10940
    laser_frame_id: "laser"
    serial_port: ""     # force not-serial
    serial_baud: 0      # optional, but makes intent clear

# Old LD19 config (unused)
# LD19:
#   ros__parameters:
#     product_name: "LDLiDAR_LD19"
#     topic_name: "scan"
#     frame_id: "laser"
#     port_name: "/dev/sensors/lidar"
#     port_baudrate: 230400
#     laser_scan_dir: true
#     enable_angle_crop_func: false
#     angle_crop_min: 0.0
#     angle_crop_max: 0.0